[build-system]
requires = []
build-backend = "madrona-py-build"
backend-path = ["external/madrona/py"]

[project]
name = "madrona_basketball"
version = "0.0.1"

[tool.madrona.packages.madrona_basketball]
ext-out-dir = "build"
ext-only = true
